# Generated by Django 2.2.6 on 2019-10-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DateTimeField(null=True)),
                ('consumo_r', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumo_s', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumo_t', models.DecimalField(decimal_places=2, max_digits=15)),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
